services:
  app:
    build: .
    container_name: go_crud
    env_file: .env
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    command: ["sh", "-c", "go mod tidy && go run ./cmd/web"]

  db:
    image: mysql:8.4
    container_name: go_crud_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./internal/db/init.sql:/docker-entrypoint-initdb.d/01_init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  dbdata:
